export enum CLIENT_ROUTES {
  HOME = "/",
  MAIN = "/main",
  REGISTRATION = "/signUp",
  LOGIN = "/signIn",
  EVENTFORM = "/eventForm",
  EVENT = "/events",
  SPORT_CLUB = "/sportclub",
  CREATE_SPORT_CLUB = "/createsportclub",
  SUBSCRIBE_TO_SPORT_CLUB = "/subscribe",
  PROFILE = "/profile",
  USER_PROFILE = "/user/:id",
  RESET_PASSWORD = "/password-reset/telegram",
  MAP = "/map",
  ADMIN = "/admin",
  IS_ADMIN = "/isAdmin",
  CHAT = "/chat",
  ALL_EVENTS_MAP = "/eventsmap",
  ONE_EVENT_MAP = "/eventmap",
  GALLERY = "/event/gallery",
  ACCESS_SPORT_CLUB = "/access-sport-club",
  VIDEO = "/video",
  MY_CHATS = "/my-chats",
}
